name: Frontend CD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout k8s manifests
        uses: actions/checkout@v4

      - name: Update image tag
        run: |
          sed -i "s|image: samitsinghhh/frontend:.*|image: samitsinghhh/frontend:${{ github.event.inputs.image_tag }}|g" k8s/deployments/frontend-deployment.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/services/frontend-service.yaml -n bedrock-chat-v2
          kubectl apply -f k8s/services/frontend-nodeport.yaml -n bedrock-chat-v2
          kubectl apply -f k8s/deployments/frontend-deployment.yaml -n bedrock-chat-v2
          kubectl wait --for=condition=ready pod -l app=frontend -n bedrock-chat-v2 --timeout=300s

      - name: Show status
        run: |
          kubectl get pods -l app=frontend -n bedrock-chat-v2
          NODE_PORT=$(kubectl get svc frontend-nodeport -n bedrock-chat-v2 -o jsonpath='{.spec.ports[0].nodePort}')
          echo "Frontend deployed! Access at: http://YOUR-EC2-IP:$NODE_PORT"
